version: '3.1'

services:
  seed1-app:
    image: johnwang412/playlist-demo:latest
    hostname: seed1-app
    environment:
      NETTY_TCP_HOST: seed1-app
      NETTY_TCP_PORT: 2552
      SEED_SYSTEM_NAME: PlaylistSystem
      SEED1_HOST: "seed1-app"
      SEED1_SYSTEM_PORT: 2552
      SEED2_HOST: "seed2-app"
      SEED2_SYSTEM_PORT: 2553
    networks:
      playlist-nw:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 20s
      update_config:
        parallelism: 1
        delay: 10s
  seed2-app:
    image: johnwang412/playlist-demo:latest
    hostname: seed2-app
    environment:
      NETTY_TCP_HOST: seed2-app
      NETTY_TCP_PORT: 2553
      SEED_SYSTEM_NAME: PlaylistSystem
      SEED1_HOST: "seed1-app"
      SEED1_SYSTEM_PORT: 2552
      SEED2_HOST: "seed2-app"
      SEED2_SYSTEM_PORT: 2553
    networks:
      playlist-nw:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 20s
      update_config:
        parallelism: 1
        delay: 10s

networks:
  playlist-nw:
    driver: overlay
