version: '3.1'

services:
  pl-app:
    image: johnwang412/playlist-demo:latest
    environment:
      NETTY_TCP_HOST: 127.0.0.1
      NETTY_TCP_PORT: 0
      # todo: figure out what the bind configs are
      NETTY_TCP_BIND_HOST: 10.200.0.1
      NETTY_TCP_BIND_PORT: 80
      SEED_SYSTEM_NAME: PlaylistSystem
      SEED1_HOST: 127.0.0.1
      SEED2_HOST: 127.0.0.1
      SEED1_SYSTEM_PORT: 2551
      SEED2_SYSTEM_PORT: 2552
    networks:
      - playlist-nw
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 20s
      update_config:
        parallelism: 1
        delay: 10s

networks:
  playlist-nw:
